[package]
name = "buildy"

edition = { workspace = true }
version = { workspace = true }

[lints]
workspace = true

[dependencies]
buildy-macros = { workspace = true }

[dev-dependencies]
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
